<a href="https://colab.research.google.com/github/codershwaz/tensorflowcourse/blob/main/udemytfsection2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [12]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.int64,
    name=None
)

In [13]:
eye_tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])>

In [16]:
fill_tensor = tf.fill([2,2,4], 5, name=None)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]]], shape=(2, 2, 4), dtype=int32)


In [17]:
ones_tensor = tf.ones(
    [1,2,3], dtype=tf.dtypes.float32, name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [18]:
tf.ones_like(fill_tensor)

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [22]:
random_normal = tf.random.normal(
    [4,3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_normal)

tf.Tensor(
[[[101.45906   99.595825]
  [100.74362   98.5795  ]
  [ 98.2839   100.69095 ]]

 [[100.42473   98.24369 ]
  [ 99.41094  101.05729 ]
  [ 99.216385 102.5174  ]]

 [[ 99.34374  100.149956]
  [100.07729   99.25638 ]
  [ 98.28384  100.72565 ]]

 [[100.5338   102.36091 ]
  [ 98.31852   99.85079 ]
  [ 98.97594  101.64603 ]]], shape=(4, 3, 2), dtype=float32)


In [23]:
random_uniform = tf.random.uniform(
    [1,10,10],
    minval=0.0,
    maxval=10,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_uniform)

tf.Tensor(
[[[8.705248   8.037423   5.0264716  8.659077   6.2036824  1.3452423
   9.123821   2.0979     2.8228903  8.491621  ]
  [9.194407   1.4772034  8.447213   6.404772   5.474632   7.911249
   4.2513647  9.82368    6.4460897  0.31682968]
  [2.0065331  7.246988   0.47390103 6.9054356  4.7880125  4.596424
   2.8702843  7.3205843  1.3986063  0.43789268]
  [4.095869   0.36989093 1.7410338  5.032921   4.7529626  9.191371
   5.976813   2.658677   5.639633   3.6122859 ]
  [1.4633107  8.727127   3.003714   2.0087755  5.378996   1.8516374
   8.473329   6.2375546  5.146202   2.413981  ]
  [5.5299425  6.8119645  8.00738    6.6239476  4.951279   3.462453
   4.1687307  2.5777352  2.649827   7.8668747 ]
  [8.187776   9.661378   5.5863485  7.6587057  5.734067   3.778044
   4.4672165  8.266927   0.6474912  7.5968637 ]
  [6.5818396  9.83415    7.2243214  5.0313807  9.933247   6.6578746
   5.0783978  5.6058884  9.372215   9.064346  ]
  [6.782604   6.4167595  4.0465045  3.7421572  7.9065456  1.071623